# Generated by Django 4.0.4 on 2022-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope_scope_articlescope_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название раздела'),
        ),
    ]
